-- LeanBox demo catalog. Generated by scripts/generate-seed.mjs — edit supabase/seed-data.mjs instead.
-- Safe to re-run: rows are upserted by id. Plans keep any stripe_price_id you have already mapped.
-- Prices are HKD cents (8800 = HK$88).

insert into public.meals (id, slug, name_zh, name_en, description_zh, description_en, ingredients_zh, ingredients_en, allergens, kcal, protein_g, carbs_g, fat_g, tags, price_cents, cost_cents, image_path, is_active, weekly_stock, sort_order) values
  ('0e1f0000-0000-4000-8000-000000000001', 'teriyaki-chicken-power-bowl', '照燒雞胸肉能量碗', 'Teriyaki Chicken Power Bowl', '香煎瘦雞胸配糙米飯與西蘭花，淋上清爽照燒風味醬汁。高蛋白飽肚之選，脂肪含量克制。', 'Lean grilled chicken breast with brown rice and broccoli, finished with a light teriyaki-style sauce. A high-protein meal designed for customers who want a filling meal without excessive fat.', '雞胸肉 — 生重 180 克
糙米飯 — 熟重 180 克
西蘭花 — 100 克
橄欖油 — 5 克
輕怡照燒醬 — 豉油、蒜、薑', 'Chicken breast — 180 g raw weight
Brown rice — 180 g cooked
Broccoli — 100 g
Olive oil — 5 g
Light teriyaki sauce — soy sauce, garlic and ginger', array['大豆', '麩質']::text[], 535, 48, 63, 10, array['高蛋白']::text[], 8800, 3200, '/food/teriyaki-chicken-power-bowl.jpg', true, 60, 10),
  ('0e1f0000-0000-4000-8000-000000000002', 'japanese-salmon-balance-bowl', '日式三文魚均衡碗', 'Japanese Salmon Balance Bowl', '香煎三文魚配糙米飯、毛豆與時蔬，蛋白質、碳水與優質脂肪三者兼備，均衡飽足。', 'Pan-seared salmon served with brown rice, edamame and mixed vegetables. A balanced meal combining high-quality protein, carbohydrates and healthy fats.', '三文魚 — 150 克
糙米飯 — 熟重 150 克
去殼毛豆 — 50 克
時蔬 — 100 克
調味 — 檸檬、黑胡椒、淡醬油', 'Salmon — 150 g
Brown rice — 150 g cooked
Shelled edamame — 50 g
Mixed vegetables — 100 g
Seasoning — lemon, pepper and light soy sauce', array['魚類', '大豆', '麩質']::text[], 625, 42, 58, 23, array['均衡']::text[], 9800, 4200, '/food/japanese-salmon-balance-bowl.jpg', true, 40, 20),
  ('0e1f0000-0000-4000-8000-000000000003', 'beef-sweet-potato-fuel-box', '牛肉番薯能量餐盒', 'Beef & Sweet Potato Fuel Box', '瘦牛肉配烤番薯、西蘭花與甘筍，以番薯作主要碳水來源，飽肚扎實的高蛋白之選。', 'Lean beef served with roasted sweet potato, broccoli and carrots. A hearty high-protein meal with sweet potato as the main carbohydrate source.', '瘦牛肉（約 5% 脂肪） — 生重 160 克
番薯 — 熟重 250 克
西蘭花與甘筍 — 100 克
食用油 — 3 克
調味 — 蒜、黑胡椒、淡醬油', 'Lean beef, approximately 5% fat — 160 g raw weight
Sweet potato — 250 g cooked
Broccoli and carrots — 100 g
Cooking oil — 3 g
Seasoning — garlic, black pepper and light soy sauce', array['大豆', '麩質']::text[], 540, 41, 62, 14, array['高蛋白', '增肌']::text[], 9800, 4000, '/food/beef-sweet-potato-fuel-box.jpg', true, 40, 30)
on conflict (id) do update set
  slug = excluded.slug,
  name_zh = excluded.name_zh,
  name_en = excluded.name_en,
  description_zh = excluded.description_zh,
  description_en = excluded.description_en,
  ingredients_zh = excluded.ingredients_zh,
  ingredients_en = excluded.ingredients_en,
  allergens = excluded.allergens,
  kcal = excluded.kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  tags = excluded.tags,
  price_cents = excluded.price_cents,
  cost_cents = excluded.cost_cents,
  image_path = excluded.image_path,
  is_active = excluded.is_active,
  weekly_stock = excluded.weekly_stock,
  sort_order = excluded.sort_order;

insert into public.plans (id, slug, name_zh, name_en, description_zh, description_en, meals_per_week, price_cents, cost_cents, stripe_price_id, is_featured, is_active, sort_order) values
  ('0e1f0000-0000-4000-9000-000000000001', 'starter-5', '輕盈計劃', 'Starter', '星期一至五，每日一個高蛋白午餐。', 'Monday to Friday — one high-protein lunch a day.', 5, 43000, 16000, null, false, true, 10),
  ('0e1f0000-0000-4000-9000-000000000002', 'balance-10', '均衡計劃', 'Balance', '星期一至五，午餐加練後晚餐。', 'Monday to Friday — lunch plus a post-training dinner.', 10, 82000, 32000, null, true, true, 20),
  ('0e1f0000-0000-4000-9000-000000000003', 'performance-14', '訓練計劃', 'Performance', '一星期七日，午餐晚餐都交畀我哋，適合密集訓練期。', 'Seven days, lunch and dinner — for heavy training blocks.', 14, 109000, 45000, null, false, true, 30)
on conflict (id) do update set
  slug = excluded.slug,
  name_zh = excluded.name_zh,
  name_en = excluded.name_en,
  description_zh = excluded.description_zh,
  description_en = excluded.description_en,
  meals_per_week = excluded.meals_per_week,
  price_cents = excluded.price_cents,
  cost_cents = excluded.cost_cents,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;

-- Map your Stripe recurring prices (test or live) to the plans, e.g.:
-- update public.plans set stripe_price_id = 'price_123' where slug = 'starter-5';
-- update public.plans set stripe_price_id = 'price_456' where slug = 'balance-10';
-- update public.plans set stripe_price_id = 'price_789' where slug = 'performance-14';
