// Generated by scripts/generate-seed.mjs — edit supabase/seed-data.mjs instead.
// Used as a read-only catalog when Supabase is not configured (demo mode).
// cost_cents (and plan stripe_price_id) are intentionally stripped: they never reach the browser.
import type { PublicMeal, PublicPlan } from "./types";

export const SEED_MEALS: PublicMeal[] = [
  {
    "id": "0e1f0000-0000-4000-8000-000000000001",
    "image_path": "/food/teriyaki-chicken-power-bowl.jpg",
    "is_active": true,
    "sort_order": 10,
    "kcal": 535,
    "slug": "teriyaki-chicken-power-bowl",
    "name_zh": "照燒雞胸肉能量碗",
    "name_en": "Teriyaki Chicken Power Bowl",
    "description_zh": "香煎瘦雞胸配糙米飯與西蘭花，淋上清爽照燒風味醬汁。高蛋白飽肚之選，脂肪含量克制。",
    "description_en": "Lean grilled chicken breast with brown rice and broccoli, finished with a light teriyaki-style sauce. A high-protein meal designed for customers who want a filling meal without excessive fat.",
    "ingredients_zh": "雞胸肉 — 生重 180 克\n糙米飯 — 熟重 180 克\n西蘭花 — 100 克\n橄欖油 — 5 克\n輕怡照燒醬 — 豉油、蒜、薑",
    "ingredients_en": "Chicken breast — 180 g raw weight\nBrown rice — 180 g cooked\nBroccoli — 100 g\nOlive oil — 5 g\nLight teriyaki sauce — soy sauce, garlic and ginger",
    "allergens": [
      "大豆",
      "麩質"
    ],
    "protein_g": 48,
    "carbs_g": 63,
    "fat_g": 10,
    "tags": [
      "高蛋白"
    ],
    "price_cents": 8800,
    "weekly_stock": 60,
    "created_at": "2026-09-28T00:00:00.000Z"
  },
  {
    "id": "0e1f0000-0000-4000-8000-000000000002",
    "image_path": "/food/japanese-salmon-balance-bowl.jpg",
    "is_active": true,
    "sort_order": 20,
    "kcal": 625,
    "slug": "japanese-salmon-balance-bowl",
    "name_zh": "日式三文魚均衡碗",
    "name_en": "Japanese Salmon Balance Bowl",
    "description_zh": "香煎三文魚配糙米飯、毛豆與時蔬，蛋白質、碳水與優質脂肪三者兼備，均衡飽足。",
    "description_en": "Pan-seared salmon served with brown rice, edamame and mixed vegetables. A balanced meal combining high-quality protein, carbohydrates and healthy fats.",
    "ingredients_zh": "三文魚 — 150 克\n糙米飯 — 熟重 150 克\n去殼毛豆 — 50 克\n時蔬 — 100 克\n調味 — 檸檬、黑胡椒、淡醬油",
    "ingredients_en": "Salmon — 150 g\nBrown rice — 150 g cooked\nShelled edamame — 50 g\nMixed vegetables — 100 g\nSeasoning — lemon, pepper and light soy sauce",
    "allergens": [
      "魚類",
      "大豆",
      "麩質"
    ],
    "protein_g": 42,
    "carbs_g": 58,
    "fat_g": 23,
    "tags": [
      "均衡"
    ],
    "price_cents": 9800,
    "weekly_stock": 40,
    "created_at": "2026-09-28T00:00:00.000Z"
  },
  {
    "id": "0e1f0000-0000-4000-8000-000000000003",
    "image_path": "/food/beef-sweet-potato-fuel-box.jpg",
    "is_active": true,
    "sort_order": 30,
    "kcal": 540,
    "slug": "beef-sweet-potato-fuel-box",
    "name_zh": "牛肉番薯能量餐盒",
    "name_en": "Beef & Sweet Potato Fuel Box",
    "description_zh": "瘦牛肉配烤番薯、西蘭花與甘筍，以番薯作主要碳水來源，飽肚扎實的高蛋白之選。",
    "description_en": "Lean beef served with roasted sweet potato, broccoli and carrots. A hearty high-protein meal with sweet potato as the main carbohydrate source.",
    "ingredients_zh": "瘦牛肉（約 5% 脂肪） — 生重 160 克\n番薯 — 熟重 250 克\n西蘭花與甘筍 — 100 克\n食用油 — 3 克\n調味 — 蒜、黑胡椒、淡醬油",
    "ingredients_en": "Lean beef, approximately 5% fat — 160 g raw weight\nSweet potato — 250 g cooked\nBroccoli and carrots — 100 g\nCooking oil — 3 g\nSeasoning — garlic, black pepper and light soy sauce",
    "allergens": [
      "大豆",
      "麩質"
    ],
    "protein_g": 41,
    "carbs_g": 62,
    "fat_g": 14,
    "tags": [
      "高蛋白",
      "增肌"
    ],
    "price_cents": 9800,
    "weekly_stock": 40,
    "created_at": "2026-09-28T00:00:00.000Z"
  }
];

export const SEED_PLANS: PublicPlan[] = [
  {
    "id": "0e1f0000-0000-4000-9000-000000000001",
    "slug": "starter-5",
    "name_zh": "輕盈計劃",
    "name_en": "Starter",
    "description_zh": "星期一至五，每日一個高蛋白午餐。",
    "description_en": "Monday to Friday — one high-protein lunch a day.",
    "meals_per_week": 5,
    "price_cents": 43000,
    "is_featured": false,
    "is_active": true,
    "sort_order": 10
  },
  {
    "id": "0e1f0000-0000-4000-9000-000000000002",
    "slug": "balance-10",
    "name_zh": "均衡計劃",
    "name_en": "Balance",
    "description_zh": "星期一至五，午餐加練後晚餐。",
    "description_en": "Monday to Friday — lunch plus a post-training dinner.",
    "meals_per_week": 10,
    "price_cents": 82000,
    "is_featured": true,
    "is_active": true,
    "sort_order": 20
  },
  {
    "id": "0e1f0000-0000-4000-9000-000000000003",
    "slug": "performance-14",
    "name_zh": "訓練計劃",
    "name_en": "Performance",
    "description_zh": "一星期七日，午餐晚餐都交畀我哋，適合密集訓練期。",
    "description_en": "Seven days, lunch and dinner — for heavy training blocks.",
    "meals_per_week": 14,
    "price_cents": 109000,
    "is_featured": false,
    "is_active": true,
    "sort_order": 30
  }
];
