export const products = [
  {
    id: "cut-chicken",
    name: "Cut Box — Chicken",
    short: "Cut · Chicken",
    tag: "Fat loss",
    kcal: 420,
    protein: 42,
    carbs: 28,
    fat: 12,
    priceHkd: 6800,
    desc: "Grilled chicken, jasmine rice, broccoli. Built for a deficit without feeling empty.",
    image: "https://images.unsplash.com/photo-1532550907401-a532c00947da?auto=format&fit=crop&w=1600&q=80",
    theme: "dark",
  },
  {
    id: "cut-salmon",
    name: "Cut Box — Salmon",
    short: "Cut · Salmon",
    tag: "Fat loss",
    kcal: 480,
    protein: 38,
    carbs: 24,
    fat: 18,
    priceHkd: 7800,
    desc: "Oven salmon, quinoa, greens. Omega-3 forward, still lean.",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1600&q=80",
    theme: "light",
  },
  {
    id: "perform-beef",
    name: "Perform Box — Beef",
    short: "Perform · Beef",
    tag: "Training",
    kcal: 620,
    protein: 48,
    carbs: 55,
    fat: 18,
    priceHkd: 8200,
    desc: "Lean beef, roasted potato, veg. For heavy squat and Hyrox days.",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1600&q=80",
    theme: "dark",
  },
  {
    id: "perform-turkey",
    name: "Perform Box — Turkey",
    short: "Perform · Turkey",
    tag: "Training",
    kcal: 560,
    protein: 46,
    carbs: 48,
    fat: 14,
    priceHkd: 7600,
    desc: "Turkey mince, rice, mixed veg. High protein, easy on the gut.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1600&q=80",
    theme: "light",
  },
  {
    id: "balance-tofu",
    name: "Balance Box — Tofu",
    short: "Balance · Tofu",
    tag: "Everyday",
    kcal: 490,
    protein: 28,
    carbs: 52,
    fat: 16,
    priceHkd: 6400,
    desc: "Firm tofu, brown rice, sesame greens. Plant-forward weekday default.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1600&q=80",
    theme: "dark",
  },
  {
    id: "pack-12",
    name: "Athlete Pack — 12 meals",
    short: "Athlete Pack",
    tag: "Best value",
    kcal: null,
    protein: null,
    carbs: null,
    fat: null,
    priceHkd: 76800,
    desc: "12 mixed boxes. Cut + Perform rotation. HK delivery included in-zone.",
    image: "https://images.unsplash.com/photo-1498837161126-2d1b0bdd0df2?auto=format&fit=crop&w=1600&q=80",
    theme: "light",
  },
];

export function formatHkd(cents) {
  return `HK$${(cents / 100).toFixed(0)}`;
}
