export const products = [
  {
    id: "cut-chicken",
    name: "Cut Box — Chicken",
    tag: "Fat loss",
    kcal: 420,
    protein: 42,
    carbs: 28,
    fat: 12,
    priceHkd: 6800,
    desc: "Grilled chicken, jasmine rice, broccoli. Built for a deficit without feeling empty.",
  },
  {
    id: "cut-salmon",
    name: "Cut Box — Salmon",
    tag: "Fat loss",
    kcal: 480,
    protein: 38,
    carbs: 24,
    fat: 18,
    priceHkd: 7800,
    desc: "Oven salmon, quinoa, greens. Omega-3 forward, still lean.",
  },
  {
    id: "perform-beef",
    name: "Perform Box — Beef",
    tag: "Training",
    kcal: 620,
    protein: 48,
    carbs: 55,
    fat: 18,
    priceHkd: 8200,
    desc: "Lean beef, roasted potato, veg. For heavy squat / Hyrox days.",
  },
  {
    id: "perform-turkey",
    name: "Perform Box — Turkey",
    tag: "Training",
    kcal: 560,
    protein: 46,
    carbs: 48,
    fat: 14,
    priceHkd: 7600,
    desc: "Turkey mince, rice, mixed veg. High protein, easy on the gut.",
  },
  {
    id: "balance-tofu",
    name: "Balance Box — Tofu",
    tag: "Everyday",
    kcal: 490,
    protein: 28,
    carbs: 52,
    fat: 16,
    priceHkd: 6400,
    desc: "Firm tofu, brown rice, sesame greens. Plant-forward weekday default.",
  },
  {
    id: "pack-12",
    name: "Athlete Pack — 12 meals",
    tag: "Best value",
    kcal: null,
    protein: null,
    carbs: null,
    fat: null,
    priceHkd: 76800,
    desc: "12 mixed boxes. We rotate Cut + Perform. HK delivery included in-zone.",
  },
];

export function formatHkd(cents) {
  return `HK$${(cents / 100).toFixed(0)}`;
}
