#!/usr/bin/env node
// Regenerates supabase/seed.sql and lib/catalog/seed-data.ts from supabase/seed-data.mjs.
//   node scripts/generate-seed.mjs
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { meals, plans } from "../supabase/seed-data.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const q = (v) => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (Array.isArray(v)) return `array[${v.map(q).join(", ")}]::text[]`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const mealCols = [
  "id", "slug", "name_zh", "name_en", "description_zh", "description_en",
  "ingredients_zh", "ingredients_en", "allergens", "kcal", "protein_g", "carbs_g", "fat_g",
  "tags", "price_cents", "cost_cents", "image_path", "is_active", "weekly_stock", "sort_order",
];
const planCols = [
  "id", "slug", "name_zh", "name_en", "description_zh", "description_en", "meals_per_week",
  "price_cents", "cost_cents", "stripe_price_id", "is_featured", "is_active", "sort_order",
];

const upsert = (table, cols, rows, conflict, keep = []) => {
  const values = rows.map((r) => `  (${cols.map((c) => q(r[c])).join(", ")})`).join(",\n");
  const updates = cols
    .filter((c) => c !== conflict && !keep.includes(c))
    .map((c) => `  ${c} = excluded.${c}`)
    .join(",\n");
  return `insert into public.${table} (${cols.join(", ")}) values\n${values}\non conflict (${conflict}) do update set\n${updates};\n`;
};

const sql = `-- LeanBox demo catalog. Generated by scripts/generate-seed.mjs — edit supabase/seed-data.mjs instead.
-- Safe to re-run: rows are upserted by id. Plans keep any stripe_price_id you have already mapped.
-- Prices are HKD cents (8800 = HK$88).

${upsert("meals", mealCols, meals, "id")}
${upsert("plans", planCols, plans, "id", ["stripe_price_id"])}
-- Map your Stripe recurring prices (test or live) to the plans, e.g.:
-- update public.plans set stripe_price_id = 'price_123' where slug = 'starter-5';
-- update public.plans set stripe_price_id = 'price_456' where slug = 'balance-10';
-- update public.plans set stripe_price_id = 'price_789' where slug = 'performance-14';
`;

writeFileSync(join(root, "supabase/seed.sql"), sql);

const publicMeals = meals.map(({ cost_cents, ...m }) => ({ ...m, created_at: "2026-09-28T00:00:00.000Z" }));
const publicPlans = plans.map(({ cost_cents, stripe_price_id, ...p }) => p);

const ts = `// Generated by scripts/generate-seed.mjs — edit supabase/seed-data.mjs instead.
// Used as a read-only catalog when Supabase is not configured (demo mode).
// cost_cents (and plan stripe_price_id) are intentionally stripped: they never reach the browser.
import type { PublicMeal, PublicPlan } from "./types";

export const SEED_MEALS: PublicMeal[] = ${JSON.stringify(publicMeals, null, 2)};

export const SEED_PLANS: PublicPlan[] = ${JSON.stringify(publicPlans, null, 2)};
`;
writeFileSync(join(root, "lib/catalog/seed-data.ts"), ts);
console.log(`Wrote seed.sql (${meals.length} meals, ${plans.length} plans) and lib/catalog/seed-data.ts`);
